version: 0.2

phases:
  install:
    commands:
      - cd globalmart-catalog
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
    - '!node_modules/**'
  base-directory: globalmart-catalog/build
